// oxlint-disable import/no-named-as-default-member
import json from '@eslint/json';
import tsParser from '@typescript-eslint/parser';
import eslintPluginAstro from 'eslint-plugin-astro';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default [
	{
		files: ['**/*.json', '.*.json'],
		ignores: ['bun.lock', '.vscode/*.json', '.zed/*.json', 'package.json'],
		language: 'json/json',
		plugins: { json },
		rules: {
			'json/no-duplicate-keys': 'error',
			'json/no-empty-keys': 'error',
			'json/no-unnormalized-keys': 'error',
			'json/no-unsafe-values': 'error',
			'json/sort-keys': 'error',
			'json/top-level-interop': 'error',
		},
	},
	{
		files: ['.vscode/*.json', '.zed/*.json'],
		language: 'json/jsonc',
		languageOptions: {
			allowTrailingCommas: true,
		},
		plugins: { json },
		rules: {
			'json/no-duplicate-keys': 'error',
			'json/no-empty-keys': 'error',
			'json/no-unnormalized-keys': 'error',
			'json/no-unsafe-values': 'error',
			'json/sort-keys': 'error',
			'json/top-level-interop': 'error',
		},
	},
	...eslintPluginAstro.configs['all'],
	...eslintPluginAstro.configs['jsx-a11y-strict'],
	{
		files: ['**/*.astro'],
		ignores: [
			'**/*.js',
			'**/*.mjs',
			'**/*.cjs',
			'**/*.ts',
			'**/*.mts',
			'**/*.cts',
			'**/*.tsx',
			'**/*.jsx',
			'**/*.json',
			'**/*.css',
			'**/*.html',
			'**/*.md',
			'**/*.yaml',
			'**/*.yml',
		],
		languageOptions: {
			parserOptions: {
				extraFileExtensions: ['.astro'],
				parser: tsParser,
			},
		},
		plugins: {
			'jsx-a11y': jsxA11y,
		},
		rules: {
			'astro/jsx-a11y/alt-text': 'error',
			'astro/jsx-a11y/anchor-ambiguous-text': 'error',
			'astro/jsx-a11y/anchor-has-content': 'error',
			'astro/jsx-a11y/anchor-is-valid': 'error',
			'astro/jsx-a11y/aria-activedescendant-has-tabindex': 'error',
			'astro/jsx-a11y/aria-props': 'error',
			'astro/jsx-a11y/aria-proptypes': 'error',
			'astro/jsx-a11y/aria-role': 'error',
			'astro/jsx-a11y/aria-unsupported-elements': 'error',
			'astro/jsx-a11y/autocomplete-valid': 'error',
			'astro/jsx-a11y/click-events-have-key-events': 'error',
			'astro/jsx-a11y/control-has-associated-label': 'error',
			'astro/jsx-a11y/heading-has-content': 'error',
			'astro/jsx-a11y/html-has-lang': 'error',
			'astro/jsx-a11y/iframe-has-title': 'error',
			'astro/jsx-a11y/img-redundant-alt': 'error',
			'astro/jsx-a11y/interactive-supports-focus': 'error',
			'astro/jsx-a11y/label-has-associated-control': 'error',
			'astro/jsx-a11y/lang': 'error',
			'astro/jsx-a11y/media-has-caption': 'error',
			'astro/jsx-a11y/mouse-events-have-key-events': 'error',
			'astro/jsx-a11y/no-access-key': 'error',
			'astro/jsx-a11y/no-aria-hidden-on-focusable': 'error',
			'astro/jsx-a11y/no-autofocus': 'error',
			'astro/jsx-a11y/no-distracting-elements': 'error',
			'astro/jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
			'astro/jsx-a11y/no-noninteractive-element-interactions': 'error',
			'astro/jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
			'astro/jsx-a11y/no-noninteractive-tabindex': 'error',
			'astro/jsx-a11y/no-redundant-roles': 'error',
			'astro/jsx-a11y/no-static-element-interactions': 'error',
			'astro/jsx-a11y/prefer-tag-over-role': 'error',
			'astro/jsx-a11y/role-has-required-aria-props': 'error',
			'astro/jsx-a11y/role-supports-aria-props': 'error',
			'astro/jsx-a11y/scope': 'error',
			'astro/jsx-a11y/tabindex-no-positive': 'error',
			'astro/missing-client-only-directive-value': 'error',
			'astro/no-conflict-set-directives': 'error',
			'astro/no-deprecated-astro-canonicalurl': 'error',
			'astro/no-deprecated-astro-fetchcontent': 'error',
			'astro/no-deprecated-astro-resolve': 'error',
			'astro/no-deprecated-getentrybyslug': 'error',
			'astro/no-exports-from-components': 'error',
			'astro/no-prerender-export-outside-pages': 'error',
			'astro/no-set-html-directive': 'error',
			'astro/no-set-text-directive': 'error',
			'astro/no-unsafe-inline-scripts': 'error',
			'astro/no-unused-css-selector': 'error',
			'astro/no-unused-define-vars-in-style': 'error',
			'astro/prefer-class-list-directive': 'error',
			'astro/prefer-object-class-list': 'error',
			'astro/prefer-split-class-list': 'error',
			'astro/sort-attributes': 'error',
			'astro/valid-compile': 'error',
		},
	},
];
